version: '3'
services:

  game_web:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    image: game/web
    container_name: game_web
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./log:/var/log:z
      - ./state:/var/lib/unit:z
      - ./settings:/home/django/settings:z
    