# Generated by Django 3.1.1 on 2021-07-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wg', '0002_template_del_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='count',
            field=models.IntegerField(null=True, verbose_name='人数'),
        ),
    ]
