# Generated by Django 3.1.1 on 2021-01-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=64, verbose_name='会議ID')),
                ('user_id', models.CharField(max_length=64, verbose_name='ユーザID')),
                ('user_name', models.CharField(max_length=128, verbose_name='ユーザ名')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='参加日時')),
                ('leave_time', models.DateTimeField(verbose_name='退室日時')),
            ],
        ),
    ]
