# Generated by Django 3.1.1 on 2020-09-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_cnt', models.IntegerField(verbose_name='人数')),
                ('start_score', models.IntegerField(verbose_name='開始スコア')),
                ('end_score', models.IntegerField(verbose_name='終了スコア')),
            ],
        ),
    ]
