# Generated by Django 3.1.1 on 2020-09-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_cnt',
            field=models.IntegerField(verbose_name='プレイヤー人数'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_no', models.IntegerField(verbose_name='プレイヤー番号')),
                ('name', models.CharField(max_length=50, verbose_name='プレイヤー名')),
                ('score', models.IntegerField(verbose_name='スコア')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linq.game')),
            ],
        ),
    ]
