# Generated by Django 3.1.1 on 2020-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0002_auto_20200921_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_no',
        ),
    ]
