# Generated by Django 3.1.1 on 2020-09-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0004_round_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='hint1',
            field=models.CharField(max_length=100, null=True, verbose_name='ヒント1'),
        ),
        migrations.AlterField(
            model_name='round',
            name='hint2',
            field=models.CharField(max_length=100, null=True, verbose_name='ヒント2'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player11', to='linq.player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player12', to='linq.player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player21',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player21', to='linq.player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player22', to='linq.player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.IntegerField(null=True, verbose_name='スコア'),
        ),
    ]
