# Generated by Django 3.1.1 on 2020-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0005_auto_20200921_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='word',
            field=models.CharField(max_length=100, verbose_name='Word'),
        ),
    ]
