# Generated by Django 3.1.1 on 2020-09-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0006_auto_20200922_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ng_hit',
            field=models.IntegerField(null=True, verbose_name='NG的中'),
        ),
        migrations.AddField(
            model_name='round',
            name='other_hit',
            field=models.IntegerField(null=True, verbose_name='他ペア的中'),
        ),
        migrations.AddField(
            model_name='round',
            name='pair_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_player', to='linq.player'),
        ),
        migrations.AddField(
            model_name='round',
            name='self_hit',
            field=models.BooleanField(null=True, verbose_name='自ペア的中'),
        ),
    ]
