# Generated by Django 3.1.1 on 2020-09-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0007_auto_20200922_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='pair_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linq.round'),
        ),
    ]
