# Generated by Django 3.1.1 on 2020-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0009_auto_20200922_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='be_ng_hit',
            field=models.IntegerField(default=0, null=True, verbose_name='被NG的中'),
        ),
        migrations.AddField(
            model_name='round',
            name='be_other_hit',
            field=models.IntegerField(default=0, null=True, verbose_name='被他ペア的中'),
        ),
    ]
