# Generated by Django 3.1.1 on 2020-09-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0010_auto_20200922_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='player11',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player12',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player21',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player22',
        ),
        migrations.AddField(
            model_name='round',
            name='poll11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll11_p', to='linq.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='poll12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll12_p', to='linq.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='poll21',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll21_p', to='linq.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='poll22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll22_p', to='linq.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pair_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_player_p', to='linq.round'),
        ),
    ]
