# Generated by Django 3.1.1 on 2020-09-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0011_auto_20200924_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='poll1_result',
            field=models.IntegerField(null=True, verbose_name='投票１結果'),
        ),
        migrations.AddField(
            model_name='round',
            name='poll2_result',
            field=models.IntegerField(null=True, verbose_name='投票２結果'),
        ),
    ]
