# Generated by Django 3.1.1 on 2020-10-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0012_auto_20200927_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='solo_cnt',
            field=models.IntegerField(default=0, verbose_name='ソロプレイヤー人数'),
            preserve_default=False,
        ),
    ]
