# Generated by Django 3.1.1 on 2021-02-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0013_game_solo_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='calc_round',
            field=models.IntegerField(default=0, verbose_name='計算済みラウンド'),
            preserve_default=False,
        ),
    ]
